import { bi, genTimeline } from './shared.js';

export const config = {
  key: 'lorry', name: bi('罗里运输', 'Lorry Transport'), emoji: '🚚',
  tagline: 'Lorry Dispatch System',
  productName: 'LorryOps', orderCode: 'DO',
  resourceLabel: bi('车辆', 'Vehicle'), staffLabel: bi('司机', 'Driver'), orderLabel: bi('送货单 DO', 'Delivery Order (DO)'),
  stageLabels: { pending: bi('待派车', 'Pending Dispatch'), active: bi('运送中', 'In Transit'), done: bi('已送达', 'Delivered') },
  fieldRole: bi('司机', 'Driver'),
  resources: [
    { id: 'LR1', code: 'JHR 1234', staff: 'Ah Seng', status: 'active', skill: bi('长途经验 8 年', 'Long-haul, 8 yrs'), skillLevel: 4, restHours: 2 },
    { id: 'LR2', code: 'JHR 5678', staff: 'Muthu', status: 'active', skill: bi('长途经验 5 年', 'Long-haul, 5 yrs'), skillLevel: 3, restHours: 3 },
    { id: 'LR3', code: 'JQR 2210', staff: 'Azman', status: 'idle', skill: bi('本地路线 3 年', 'Local routes, 3 yrs'), skillLevel: 2, restHours: 10 },
    { id: 'LR4', code: 'JHR 8899', staff: 'Lim', status: 'problem', skill: bi('长途经验 6 年', 'Long-haul, 6 yrs'), skillLevel: 4, restHours: 1 },
    { id: 'LR5', code: 'JQR 4471', staff: 'Rajesh', status: 'active', skill: bi('长途经验 4 年', 'Long-haul, 4 yrs'), skillLevel: 3, restHours: 2 },
    { id: 'LR6', code: 'JHR 3302', staff: 'Faizal', status: 'idle', skill: bi('长途经验 9 年', 'Long-haul, 9 yrs'), skillLevel: 5, restHours: 11 },
    { id: 'LR7', code: 'JHR 7765', staff: 'Tan', status: 'active', skill: bi('本地路线 6 年', 'Local routes, 6 yrs'), skillLevel: 3, restHours: 3 },
    { id: 'LR8', code: 'JQR 9081', staff: 'Kumar', status: 'idle', skill: bi('长途经验 2 年', 'Long-haul, 2 yrs'), skillLevel: 2, restHours: 6 },
  ],
  orders: [
    { id: 'L01', customer: 'Teck Heng 五金 Sdn Bhd', route: 'Pasir Gudang → Senai', content: bi('钢材 20 包', 'Steel bars, 20 bundles'), amount: 850, status: 'problem', resourceId: 'LR4', problemNote: bi('车辆在 Senai 收费站附近抛锚，已联络拖车，预计延误 2 小时', 'Vehicle broke down near Senai toll, tow truck contacted, ETA delay ~2 hours'), timeline: genTimeline('problem', 8, 10) },
    { id: 'L02', customer: 'Kulai Timber Sdn Bhd', route: 'Skudai → Kulai', content: bi('木材 15 捆', 'Timber, 15 bundles'), amount: 620, status: 'pending', timeline: genTimeline('pending', 9, 0) },
    { id: 'L03', customer: 'Ban Guan Industries', route: 'JB → Batu Pahat', content: bi('包装原料 30 箱', 'Packaging materials, 30 boxes'), amount: 980, status: 'active', resourceId: 'LR1', timeline: genTimeline('active', 8, 30) },
    { id: 'L04', customer: 'Hup Seng 五金', route: 'JB → Singapore', content: bi('五金配件 一批（过关）', 'Hardware parts, mixed lot (customs clearance)'), amount: 1450, status: 'active', resourceId: 'LR2', timeline: genTimeline('active', 7, 45) },
    { id: 'L05', customer: 'Evergreen 工业', route: 'Pasir Gudang → Senai', content: bi('塑料原料 25 包', 'Plastic raw material, 25 bags'), amount: 760, status: 'active', resourceId: 'LR5', timeline: genTimeline('active', 9, 15) },
    { id: 'L06', customer: 'Kim Huat Sdn Bhd', route: 'Skudai → Kulai', content: bi('建材 一批', 'Building materials, mixed lot'), amount: 890, status: 'active', resourceId: 'LR7', timeline: genTimeline('active', 10, 0) },
    { id: 'L07', customer: 'Soon Lee 五金', route: 'JB → Batu Pahat', content: bi('钢管 40 支', 'Steel pipes, 40 units'), amount: 1100, status: 'done', paid: true, resourceId: 'LR3', timeline: genTimeline('done', 7, 0) },
    { id: 'L08', customer: 'Chong Wah Industries', route: 'Pasir Gudang → Senai', content: bi('纸箱 一批', 'Cartons, mixed lot'), amount: 430, status: 'done', paid: true, resourceId: 'LR6', timeline: genTimeline('done', 7, 20) },
    { id: 'L09', customer: 'Teo Brothers Sdn Bhd', route: 'JB → Singapore', content: bi('电子零件（过关）', 'Electronic parts (customs clearance)'), amount: 2100, status: 'done', paid: false, resourceId: 'LR8', timeline: genTimeline('done', 6, 50) },
    { id: 'L10', customer: 'Ah Hock 五金', route: 'Skudai → Kulai', content: bi('水管配件', 'Plumbing fittings'), amount: 540, status: 'done', paid: true, resourceId: 'LR1', timeline: genTimeline('done', 6, 30) },
    { id: 'L11', customer: 'Guan Chong Sdn Bhd', route: 'JB → Batu Pahat', content: bi('五金 一批', 'Hardware, mixed lot'), amount: 675, status: 'done', paid: false, resourceId: 'LR2', timeline: genTimeline('done', 7, 40) },
    { id: 'L12', customer: 'Lim Trading 五金', route: 'Pasir Gudang → Senai', content: bi('包装材料', 'Packaging materials'), amount: 510, status: 'pending', timeline: genTimeline('pending', 10, 20) },
  ],
  monthly: [
    { code: 'JHR 1234', staff: 'Ah Seng', count: 18, revenue: 6400, cost: 1850 },
    { code: 'JHR 5678', staff: 'Muthu', count: 22, revenue: 7900, cost: 2100 },
    { code: 'JQR 2210', staff: 'Azman', count: 15, revenue: 5200, cost: 1400 },
    { code: 'JHR 8899', staff: 'Lim', count: 12, revenue: 4100, cost: 1600 },
    { code: 'JQR 4471', staff: 'Rajesh', count: 20, revenue: 7100, cost: 1950 },
    { code: 'JHR 3302', staff: 'Faizal', count: 16, revenue: 5600, cost: 1500 },
    { code: 'JHR 7765', staff: 'Tan', count: 19, revenue: 6800, cost: 1800 },
    { code: 'JQR 9081', staff: 'Kumar', count: 14, revenue: 4850, cost: 1350 },
  ],
  unpaid: 4320,
  fieldTasks: [
    { id: 'FT1', title: 'Ban Guan Industries — JB → Batu Pahat', loc: bi('钢材原料 30 箱', 'Steel raw material, 30 boxes'), step: 1 },
    { id: 'FT2', title: 'Hup Seng 五金 — JB → Singapore', loc: bi('五金配件（过关文件已备）', 'Hardware parts (customs docs ready)'), step: 0 },
    { id: 'FT3', title: 'Soon Lee 五金 — JB → Batu Pahat', loc: bi('钢管 40 支', 'Steel pipes, 40 units'), step: 3 },
  ],
  automations: [
    { title: bi('单据自动生成', 'Auto-generate documents'), pain: bi('省掉每天重复抄写路线、客户、运费 2 小时', 'Saves 2 hours/day of re-typing routes, customers, fees'), preview: 'doc', previewData: { title: bi('送货单 DO-2026091', 'Delivery Order DO-2026091'), lines: [bi('客户：Ban Guan Industries', 'Customer: Ban Guan Industries'), bi('路线：JB → Batu Pahat', 'Route: JB → Batu Pahat'), bi('运费：RM 980  已自动生成发票 INV-2026091', 'Fee: RM 980 — Invoice INV-2026091 auto-generated')] } },
    { title: bi('状态变更自动 WhatsApp 通知客户', 'Auto WhatsApp update on status change'), pain: bi('不用再接十几通「到了没」的电话', "No more answering a dozen 'has it arrived?' calls"), preview: 'wa', previewData: { text: bi('Lorry JHR 1234 已 Delivered ✅\n签收时间 14:32\n谢谢惠顾 Ban Guan Industries', 'Lorry JHR 1234 has been Delivered ✅\nSigned at 14:32\nThank you Ban Guan Industries') } },
    { title: bi('月结 / 应收账款自动汇总', 'Auto monthly closing / receivables summary'), pain: bi('月底 3 天对账变成自动列表，压 60 天账期自动标红', '3-day month-end reconciliation becomes an automatic list; accounts 60+ days overdue auto-flagged red'), preview: 'text', previewData: bi('⚠ Teo Brothers Sdn Bhd 已欠款 RM 2,100，超过账期 63 天', '⚠ Teo Brothers Sdn Bhd owes RM 2,100, 63 days overdue') },
    { title: bi('罗厘牌照 / 保险 / Puspakom 检验到期提醒', 'Road tax / insurance / Puspakom inspection expiry alerts'), pain: bi('避免罚款、车被扣，油卡对账不再靠人工核', 'Avoid fines and vehicle seizure; fuel card reconciliation no longer manual'), preview: 'text', previewData: bi('⚠ JHR 8899 Road Tax 还有 5 天到期 · Puspakom 检验还有 12 天', '⚠ JHR 8899 Road Tax expires in 5 days · Puspakom inspection in 12 days') },
  ],
};


export const workflow = {
    stages: [
      ['request', bi('客户询价', 'Customer request')],
      ['quotation', bi('报价', 'Quotation')],
      ['confirmed', bi('确认下单', 'Confirmed')],
      ['planning', bi('调度规划', 'Planning')],
      ['assigned', bi('已分派', 'Assigned')],
      ['pickup', bi('取货', 'Pickup')],
      ['delivery', bi('送货中', 'Delivery')],
      ['pod', bi('签收凭证', 'Proof of delivery')],
      ['invoicing', bi('开发票', 'Invoicing')],
      ['payment', bi('收款', 'Payment')],
      ['reported', bi('已入账', 'Reported')],
    ],
    idPrefix: 'REQ',
    sequence: 109,
    items: [
      { id: 'REQ-0101', customer: 'Kulai Timber Sdn Bhd', phone: '+60 12-882 1042', route: 'Skudai → Kulai', cargo: 'Timber, 15 bundles', amount: 620, stage: 'request', source: 'WhatsApp', automation: bi('等待货物重量资料', 'Waiting for cargo weight'), needsAttention: true, age: '8 min' },
      { id: 'REQ-0102', customer: 'Lim Trading Hardware', phone: '+60 17-441 8200', route: 'Pasir Gudang → Senai', cargo: 'Packaging materials', amount: 510, stage: 'quotation', source: 'WhatsApp', automation: bi('报价单 QT-0102 已生成', 'Quote QT-0102 prepared'), needsApproval: true, age: '14 min' },
      { id: 'JOB-0103', customer: 'Southern Cable Industries', phone: '+60 16-225 3411', route: 'Tebrau → Tanjung Pelepas', cargo: 'Cable drums, 4 units', amount: 1280, stage: 'confirmed', source: 'Web form', automation: bi('客户已于 09:42 确认', 'Customer accepted at 09:42'), age: '22 min' },
      { id: 'JOB-0104', customer: 'Hup Seng Hardware', phone: '+60 12-771 9002', route: 'JB → Singapore', cargo: 'Hardware parts, customs', amount: 1450, stage: 'planning', source: 'Recurring', automation: bi('正在核实过关证件与车位', 'Checking permit and capacity'), needsAttention: true, age: '31 min' },
      { id: 'JOB-0105', customer: 'Ban Guan Industries', phone: '+60 19-550 7331', route: 'JB → Batu Pahat', cargo: 'Packaging materials, 30 boxes', amount: 980, stage: 'assigned', source: 'WhatsApp', automation: bi('Ah Seng · JHR 1234', 'Ah Seng · JHR 1234'), age: '48 min' },
      { id: 'JOB-0106', customer: 'Evergreen Industrial', phone: '+60 11-209 4432', route: 'Pasir Gudang → Senai', cargo: 'Plastic raw material, 25 bags', amount: 760, stage: 'delivery', source: 'Phone', automation: bi('预计 14:35 送达 · 准时', 'ETA 14:35 · on time'), age: '2 hr' },
      { id: 'JOB-0107', customer: 'Soon Lee Hardware', phone: '+60 13-663 2018', route: 'JB → Batu Pahat', cargo: 'Steel pipes, 40 units', amount: 1100, stage: 'pod', source: 'WhatsApp', automation: bi('已签收 · 缺少照片', 'Signature received · photo missing'), needsAttention: true, age: '3 hr' },
      { id: 'INV-0108', customer: 'Chong Wah Industries', phone: '+60 16-881 0034', route: 'Pasir Gudang → Senai', cargo: 'Cartons, mixed lot', amount: 430, stage: 'payment', source: 'Recurring', automation: bi('发票 7 天后到期', 'Invoice due in 7 days'), age: '2 days' },
    ],
    events: [
      { id: 1, time: '10:18', text: bi('已发送客户进度更新 JOB-0106', 'Customer update sent for JOB-0106'), type: 'message' },
      { id: 2, time: '10:12', text: bi('JOB-0107 签收单已核实', 'POD signature verified for JOB-0107'), type: 'document' },
      { id: 3, time: '09:58', text: bi('Ah Seng 已分派至 JOB-0105', 'Ah Seng assigned to JOB-0105'), type: 'assignment' },
      { id: 4, time: '09:42', text: bi('JOB-0103 报价已被接受', 'Quotation accepted for JOB-0103'), type: 'payment' },
    ],
    messages: {
      quotation: bi('已核算标准价，报价单已生成', 'Standard price calculated · quote ready'),
      confirmed: bi('客户已接受报价，工单已建立', 'Quotation accepted · job created'),
      planning: bi('车位与班次检查已通过', 'Capacity and schedule checks passed'),
      assigned: bi('已分派最合适的司机与车辆', 'Best available driver and vehicle assigned'),
      pickup: bi('司机已出发取货', 'Driver dispatched to pickup'),
      delivery: bi('货物已取货，客户已收到通知', 'Cargo picked up · customer notified'),
      pod: bi('已送达 · 正在收集签收凭证', 'Delivered · collecting proof of delivery'),
      invoicing: bi('签收单已核实，发票已生成', 'POD verified · invoice generated'),
      payment: bi('发票已寄出，账期追踪中', 'Invoice sent · monitoring due date'),
      reported: bi('款项已核对，报表已更新', 'Payment matched · reports updated'),
    },
};
