import { bi, genTimeline } from './shared.js';

export const config = {
  key: 'supplier', name: bi('五金批发', 'Hardware Wholesale'), emoji: '📦',
  tagline: 'Supplier Order Tracker',
  productName: 'StockOps', orderCode: 'SO',
  resourceLabel: bi('打包台', 'Packing Station'), staffLabel: bi('理货员', 'Picker'), orderLabel: bi('销售单 SO', 'Sales Order (SO)'),
  stageLabels: { pending: bi('待处理', 'Pending'), active: bi('备货中', 'Picking'), done: bi('已交货', 'Delivered') },
  fieldRole: bi('理货员', 'Picker'),
  resources: [
    { id: 'SB1', code: '打包台 1', staff: 'Ah Seng', status: 'active', skill: bi('五金分类熟练', 'Hardware SKU expert'), skillLevel: 4, restHours: 2 },
    { id: 'SB2', code: '打包台 2', staff: 'Muthu', status: 'active', skill: bi('建材分类熟练', 'Building materials expert'), skillLevel: 3, restHours: 3 },
    { id: 'SB3', code: '打包台 3', staff: 'Azman', status: 'idle', skill: bi('一般理货', 'General picking'), skillLevel: 2, restHours: 9 },
    { id: 'SB4', code: '打包台 4', staff: 'Lim', status: 'problem', skill: bi('油品分类熟练', 'Lubricants expert'), skillLevel: 4, restHours: 1 },
    { id: 'SB5', code: '打包台 5', staff: 'Rajesh', status: 'active', skill: bi('五金分类熟练', 'Hardware SKU expert'), skillLevel: 3, restHours: 2 },
    { id: 'SB6', code: '打包台 6', staff: 'Faizal', status: 'idle', skill: bi('建材分类熟练', 'Building materials expert'), skillLevel: 5, restHours: 12 },
    { id: 'SB7', code: '打包台 7', staff: 'Tan', status: 'active', skill: bi('一般理货', 'General picking'), skillLevel: 3, restHours: 4 },
    { id: 'SB8', code: '打包台 8', staff: 'Kumar', status: 'idle', skill: bi('油品分类熟练', 'Lubricants expert'), skillLevel: 2, restHours: 5 },
  ],
  orders: [
    { id: 'S01', customer: 'Kim Huat 汽车维修', route: '', content: bi('刹车皮 + 机油 一批', 'Brake pads + engine oil, mixed lot'), amount: 450, status: 'problem', resourceId: 'SB4', problemNote: bi('刹车皮库存不足，已联络厂商补货，预计延迟 2 天', 'Brake pad stock insufficient, manufacturer restock requested, ~2 day delay'), timeline: genTimeline('problem', 9, 0) },
    { id: 'S02', customer: 'Teck Heng 运输 Sdn Bhd', route: '', content: bi('螺丝五金 一批', 'Screws & fasteners, mixed lot'), amount: 320, status: 'pending', timeline: genTimeline('pending', 9, 20) },
    { id: 'S03', customer: 'Ban Guan 装修工程', route: '', content: bi('铝料配件 一批', 'Aluminium fittings, mixed lot'), amount: 680, status: 'active', resourceId: 'SB1', timeline: genTimeline('active', 8, 30) },
    { id: 'S04', customer: 'Hup Seng 汽修', route: '', content: bi('冷气零件 一批', 'AC parts, mixed lot'), amount: 540, status: 'active', resourceId: 'SB2', timeline: genTimeline('active', 9, 0) },
    { id: 'S05', customer: 'Evergreen Transport', route: '', content: bi('油品耗材 一批', 'Lubricants & consumables, mixed lot'), amount: 890, status: 'active', resourceId: 'SB5', timeline: genTimeline('active', 9, 30) },
    { id: 'S06', customer: 'Kim Huat 建材行', route: '', content: bi('五金工具 一批', 'Hardware tools, mixed lot'), amount: 410, status: 'active', resourceId: 'SB7', timeline: genTimeline('active', 10, 0) },
    { id: 'S07', customer: 'Soon Lee 装修', route: '', content: bi('电线电缆 一批', 'Wiring & cables, mixed lot'), amount: 720, status: 'done', paid: true, resourceId: 'SB3', timeline: genTimeline('done', 7, 0) },
    { id: 'S08', customer: 'Chong Wah 汽修厂', route: '', content: bi('滤芯 + 皮带 一批', 'Filters + belts, mixed lot'), amount: 380, status: 'done', paid: true, resourceId: 'SB6', timeline: genTimeline('done', 7, 20) },
    { id: 'S09', customer: 'Teo Brothers Transport', route: '', content: bi('油品 + 零件 一批', 'Lubricants + parts, mixed lot'), amount: 1250, status: 'done', paid: false, resourceId: 'SB8', timeline: genTimeline('done', 6, 50) },
    { id: 'S10', customer: 'Ah Hock 五金行', route: '', content: bi('螺丝螺帽 一批', 'Nuts & bolts, mixed lot'), amount: 260, status: 'done', paid: true, resourceId: 'SB1', timeline: genTimeline('done', 6, 30) },
    { id: 'S11', customer: 'Guan Chong 装修工程', route: '', content: bi('铝门窗配件 一批', 'Aluminium door/window fittings, mixed lot'), amount: 980, status: 'done', paid: false, resourceId: 'SB2', timeline: genTimeline('done', 7, 40) },
    { id: 'S12', customer: 'Lim Trading 汽修', route: '', content: bi('刹车油 + 冷气水 一批', 'Brake fluid + coolant, mixed lot'), amount: 300, status: 'pending', timeline: genTimeline('pending', 10, 15) },
  ],
  monthly: [
    { code: '打包台 1', staff: 'Ah Seng', count: 26, revenue: 8200, cost: 5400 },
    { code: '打包台 2', staff: 'Muthu', count: 22, revenue: 7100, cost: 4650 },
    { code: '打包台 3', staff: 'Azman', count: 19, revenue: 6000, cost: 3950 },
    { code: '打包台 4', staff: 'Lim', count: 14, revenue: 4400, cost: 2950 },
    { code: '打包台 5', staff: 'Rajesh', count: 24, revenue: 7600, cost: 5000 },
    { code: '打包台 6', staff: 'Faizal', count: 18, revenue: 5700, cost: 3750 },
    { code: '打包台 7', staff: 'Tan', count: 21, revenue: 6650, cost: 4400 },
    { code: '打包台 8', staff: 'Kumar', count: 16, revenue: 5100, cost: 3350 },
  ],
  unpaid: 7580,
  fieldTasks: [
    { id: 'FT1', title: 'Ban Guan 装修工程 — 铝料配件', loc: bi('拣货 + 打包', 'Picking + packing'), step: 1 },
    { id: 'FT2', title: 'Hup Seng 汽修 — 冷气零件', loc: bi('拣货中', 'Picking in progress'), step: 0 },
    { id: 'FT3', title: 'Soon Lee 装修 — 电线电缆', loc: bi('已装车待发', 'Loaded, ready to dispatch'), step: 3 },
  ],
  automations: [
    { title: bi('销售单 / 送货单 / 发票自动生成', 'Auto-generate SO / DO / invoice'), pain: bi('省掉每张单重复抄品项、数量、价钱', 'Saves re-writing items, quantities, prices on every order'), preview: 'doc', previewData: { title: bi('销售单 SO-0847', 'Sales Order SO-0847'), lines: [bi('客户：Ban Guan 装修工程', 'Customer: Ban Guan Renovation'), bi('品项：铝料配件 一批', 'Items: Aluminium fittings, mixed lot'), bi('金额：RM 680  已自动生成发票 INV-0847', 'Amount: RM 680 — Invoice INV-0847 auto-generated')] } },
    { title: bi('备货 / 配送状态自动 WhatsApp 通知客户', 'Auto WhatsApp status update to customer'), pain: bi('不用再接电话「货备好了没」', 'No more calls asking "is my order ready yet"'), preview: 'wa', previewData: { text: bi('Ban Guan 装修工程 您好，订单 SO-0847 已备货完成，今日下午送达 📦', 'Hi Ban Guan Renovation, your order SO-0847 is packed and will be delivered this afternoon 📦') } },
    { title: bi('应收账款自动汇总，压账期自动标红', 'Auto receivables summary, overdue accounts auto-flagged'), pain: bi('批发生意靠账期做生意，谁欠多久一眼看清', 'Wholesale runs on credit terms — see who owes what, for how long, at a glance'), preview: 'text', previewData: bi('⚠ Teo Brothers Transport 欠款 RM 1,250，账期 45 天已超期', '⚠ Teo Brothers Transport owes RM 1,250, 45-day term already overdue') },
    { title: bi('库存低水位自动提醒补货', 'Low-stock auto reorder alerts'), pain: bi('避免缺货流失订单，也不会囤太多压资金', 'Avoid losing orders to stockouts, without overstocking and tying up cash'), preview: 'text', previewData: bi('⚠ 刹车皮（Brake Pad）库存仅剩 8 件，低于安全水位', '⚠ Brake pads down to 8 units, below safety stock level') },
  ],
};


export const workflow = {
    stages: [
      ['request', bi('客户询价', 'Customer inquiry')],
      ['quotation', bi('报价', 'Quotation')],
      ['confirmed', bi('确认下单', 'Confirmed')],
      ['picking', bi('拣货中', 'Picking')],
      ['packed', bi('打包完成', 'Packed')],
      ['dispatched', bi('已出货', 'Dispatched')],
      ['delivered', bi('已送达', 'Delivered')],
      ['pod', bi('签收凭证', 'Proof of delivery')],
      ['invoicing', bi('开发票', 'Invoicing')],
      ['payment', bi('收款', 'Payment')],
      ['reported', bi('已入账', 'Reported')],
    ],
    idPrefix: 'REQ',
    sequence: 220,
    items: [
      { id: 'REQ-2201', customer: 'Kim Huat 汽车维修', phone: '+60 12-345 6789', route: '仓库自取', cargo: '刹车皮 + 机油 一批', amount: 450, stage: 'request', source: 'WhatsApp', automation: bi('正在核对库存与报价', 'Checking stock and preparing quote'), needsAttention: true, age: '6 min' },
      { id: 'REQ-2202', customer: 'Lim Trading 五金', phone: '+60 17-220 3390', route: 'Pasir Gudang 送货', cargo: '五金工具 一批', amount: 410, stage: 'quotation', source: 'WhatsApp', automation: bi('报价单 QT-2202 已生成', 'Quote QT-2202 prepared'), needsApproval: true, age: '12 min' },
      { id: 'SO-2203', customer: 'Ban Guan 装修工程', phone: '+60 19-550 7331', route: 'JB → Batu Pahat', cargo: '铝料配件 一批', amount: 680, stage: 'confirmed', source: 'Web form', automation: bi('客户已确认，销售单已生成', 'Customer confirmed · sales order created'), age: '20 min' },
      { id: 'SO-2204', customer: 'Hup Seng 汽修', phone: '+60 12-771 9002', route: 'JB → Singapore', cargo: '冷气零件 一批', amount: 540, stage: 'picking', source: 'Recurring', automation: bi('打包台 2 · 理货员 Muthu 拣货中', 'Packing Station 2 · Muthu picking'), needsAttention: true, age: '28 min' },
      { id: 'SO-2205', customer: 'Evergreen Transport', phone: '+60 11-209 4432', route: 'Pasir Gudang → Senai', cargo: '油品耗材 一批', amount: 890, stage: 'packed', source: 'Phone', automation: bi('打包完成，等待安排出货', 'Packed · awaiting dispatch slot'), age: '40 min' },
      { id: 'SO-2206', customer: 'Soon Lee 装修', phone: '+60 13-663 2018', route: 'JB → Batu Pahat', cargo: '电线电缆 一批', amount: 720, stage: 'dispatched', source: 'WhatsApp', automation: bi('已出货，预计 2 小时送达', 'Dispatched · ETA 2 hours'), age: '1 hr' },
      { id: 'SO-2207', customer: 'Chong Wah 汽修厂', phone: '+60 16-881 0034', route: 'Pasir Gudang → Senai', cargo: '滤芯 + 皮带 一批', amount: 380, stage: 'pod', source: 'Recurring', automation: bi('客户已签收 · 缺少照片', 'Customer signed · photo missing'), needsAttention: true, age: '2 hr' },
      { id: 'INV-2208', customer: 'Teo Brothers Transport', phone: '+60 12-990 1122', route: 'JB → Singapore', cargo: '油品 + 零件 一批', amount: 1250, stage: 'payment', source: 'Recurring', automation: bi('发票已逾期，账期 45 天', 'Invoice overdue · 45-day term'), needsAttention: true, age: '2 days' },
    ],
    events: [
      { id: 1, time: '10:18', text: bi('已发送出货通知 SO-2206', 'Dispatch notice sent for SO-2206'), type: 'message' },
      { id: 2, time: '10:12', text: bi('SO-2207 签收单已核实', 'POD signature verified for SO-2207'), type: 'document' },
      { id: 3, time: '09:58', text: bi('Muthu 已分派至 SO-2204', 'Muthu assigned to SO-2204'), type: 'assignment' },
      { id: 4, time: '09:42', text: bi('SO-2203 报价已被接受', 'Quotation accepted for SO-2203'), type: 'payment' },
    ],
    messages: {
      quotation: bi('库存已核对，报价单已生成', 'Stock checked · quote ready'),
      confirmed: bi('客户已确认下单，销售单已生成', 'Customer confirmed · sales order created'),
      picking: bi('已分配打包台与理货员拣货', 'Packing station and picker assigned'),
      packed: bi('打包完成，等待安排出货', 'Packed · awaiting dispatch slot'),
      dispatched: bi('已出货，客户已收到 WhatsApp 通知', 'Dispatched · customer notified via WhatsApp'),
      delivered: bi('货物已送达，等待客户签收', 'Delivered · awaiting customer signature'),
      pod: bi('已送达 · 正在收集签收凭证', 'Delivered · collecting proof of delivery'),
      invoicing: bi('签收单已核实，发票已生成', 'POD verified · invoice generated'),
      payment: bi('发票已寄出，账期追踪中', 'Invoice sent · monitoring due date'),
      reported: bi('款项已核对，报表已更新', 'Payment matched · reports updated'),
    },
};
